# Generated by Django 4.1.7 on 2023-02-24 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendships',
            new_name='Friendship',
        ),
    ]
