version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - ./data/db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=twitter
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/code
    entrypoint: [ "/code/wait-for-it.sh", "db:3306", "--" ]
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9091"
    restart: always
    ports:
      - "9091:9091"
    environment:
      - MYSQL_NAME=twitter
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_HOST=db
    depends_on:
      - db
      - cache
      - redis
    links:
      - db
  cache:
    image: memcached
    ports:
      - "11311:11311"
    entrypoint:
      - memcached
      - -m 64
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis-data:/data
